services:
  nuxt_ui_front:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: node .output/server/index.mjs
    env_file:
      - .env
    networks:
      - jungler-backbone
